version: '3'
services:
  db:
    image: 'postgres:latest'
    user: "${UID_GID}"
    environment:
      POSTGRES_USER: life_log
      POSTGRES_PASSWORD: life_log
      POSTGRES_DB: life_log
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
  app:
    build: .
    user: "${UID_GID}"
    restart: always
    environment:
      POSTGRES_USER: life_log
      POSTGRES_PASSWORD: life_log
      POSTGRES_DB: life_log
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    links:
      - db
